# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          wingpgmr
baseurl:        ""
url:            "http://wingpgmr.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         wingpgmr
  url:          http://wingpgmr.github.io/
  email:        wingpgmr@gmail.com  
  github:       wingpgmr
  facebook:     wingpgmr

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/wingpgmr/wingpgmr.github.io
